const queue = new Queue();
queue.push(1);
queue.push(2);
queue.push(3);
queue.push(4);
queue.push(5);
queue.push(6);
console.log(queue.pull());
console.log(queue.peek());
console.log(queue.size);
console.log(queue.isEmpty());
console.log(queue.pull());
console.log(queue.pull());
console.log(queue.pull());
console.log(queue.pull());
console.log(queue.pull());
console.log(queue.isEmpty());